# Generated by Django 5.1 on 2024-09-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
