# Generated by Django 5.1 on 2024-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_company_link_blogpost_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='photos/%y/%m/%d/'),
        ),
    ]
