# Generated by Django 5.1 on 2024-09-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
    ]
